### ISSUE TITLE
Open last online repository and remember last login

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLCanvas#111]
If I have a design and want to assign parts from an online repository, instead of specifying each time from which repository I want the part to be downloaded, I want SBOLCanvas to show me parts from the last one used, as does iBioSim.

**Comment by cjmyers** [comment]
Should also remember login information.

**Comment by LukasBuecherl** [comment]
I think this one can be closed. After login in once I remain logged in until I open a new window. Or is the goal to be logged in even when opening a new tab ?

**Comment by Randoom97** [comment]
I think the intention of remembering the login is to have it work if you close/re-open the page. That also doesn't address the issue of resetting the repository/collection every time the import component button is used, so this should probably stay open.

**Comment by cjmyers** [comment]
I agree with @Randoom97 on this.  Remembering the last collection is a big part of this issue.
