### ISSUE TITLE
Error while trying to save a design

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLCanvas#112]
The following error pops up when trying to save a design:

Error
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.ArrayIndexOutOfBoundsException </pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.36</h3></body></html>

**Comment by ImperialiGEM2020** [comment]
We've encountered this as well on Chrome and Safari with designs that are downloaded from synbiohub, trashing the design also does not work unless the page is reloaded. Saving and deleting parts that were designed directly on the Canvas however is still possible and does not throw the same error as with eg. iGEM parts.

**Comment by Randoom97** [comment]
I believe I've figured out what's causing the index out of bounds error, but could you explain trashing the design more?

**Comment by ImperialiGEM2020** [comment]
So after a part is imported from the igem collection, selecting it and then clicking the "Delete selected parts" icon does not remove the part; the subcomponent parts can also not be removed individually. When the page is reloaded, the imported part disappears. However, building a new construct on the empty canvas from scratch with parts from the toolbox does allow for the whole construct / for individual subcomponents to be removed.

**Comment by Randoom97** [comment]
I've moved this to it's own issue as I've got a fix for the index out of bounds I would like to create a pull request for that would close this issue. I've asked a follow up question in #113 if you could respond. Thanks.
