### ISSUE TITLE
Deleting parts doesn't work.

### ISSUE THREAD

**Issue by Randoom97** [SynBioDex/SBOLCanvas#113]
So after a part is imported from the igem collection, selecting it and then clicking the "Delete selected parts" icon does not remove the part; the subcomponent parts can also not be removed individually. When the page is reloaded, the imported part disappears. However, building a new construct on the empty canvas from scratch with parts from the toolbox does allow for the whole construct / for individual subcomponents to be removed.

_Originally posted by @ImperialiGEM2020 in https://github.com/SynBioDex/SBOLCanvas/issues/112#issuecomment-655773107_

**Comment by Randoom97** [comment]
I haven't been able to reproduce this. Selecting an imported component (not the backbone) and clicking delete works, trying to delete a sub component brings up a popup like this  
![image](https://user-images.githubusercontent.com/8031223/87064303-c15fed80-c1cc-11ea-98f5-c3c0fd6fbff7.png) clicking ok deletes the part. Are you recieving this popup @ImperialiGEM2020 ?

Selecting the backbone and clicking delete while in component mode doesn't currently do anything, which was intended behavior, but I can see it being more useful to remove all components on that backbone.

**Comment by ImperialiGEM2020** [comment]
So while deleting the whole design (part BBa_K1444010 downloaded from the iGEM collection) does not work, deleting the individual subcomponents does bring up this error and then allows the subcomponent to be deleted when the Delete icon is clicked. 

This is the selection before clicking the delete icon:
<img width="407" alt="Screenshot 2020-07-10 at 19 27 04" src="https://user-images.githubusercontent.com/60446814/87182096-bea3ec00-c2e3-11ea-9201-8a273f3b79b8.png">

and this is immediately after:
<img width="386" alt="Screenshot 2020-07-10 at 19 27 13" src="https://user-images.githubusercontent.com/60446814/87182141-d9766080-c2e3-11ea-81f7-f68d20a27fb3.png">

It is not the most pressing issue as deletion of the subcomponents is more important that deletion of the whole construct.
