### ISSUE TITLE
Select target of inhibition

### ISSUE THREAD

**Issue by kevinwkeating** [SynBioDex/SBOLCanvas#117]
If you have the product of a CDS inhibiting a promoter, is there a way you could select the CDS part, then shift+click or ctrl+click to select the inhibited promoter, then click on the inhibitor button? The current scheme of pulling on the anchor points isn't working very well and makes it hard to draw the relationship.

**Comment by cjmyers** [comment]
This is already supported.  It is CMD-Click on Mac, and ctrl-click on Windows, I think.  Please check it out.
