### ISSUE TITLE
CSS style for number input scroll wheel negatively affects color chooser

### ISSUE THREAD

**Issue by Samonella7** [SynBioDex/SBOLCanvas#12]

**Comment by cjmyers** [comment]
@Samonella7 What do you mean by this one?

**Comment by Samonella7** [comment]
![Capture](https://user-images.githubusercontent.com/21229771/78088457-763e6f00-7381-11ea-9328-4d4dcce25c3a.PNG)

The "scroll wheel," ie the arrows for dialing the RBG values up and down, overlap the numbers and overall look bad. 

IIRC the CSS causing this was added for other number inputs in the design menu, for example opacity. Thanks to Angular being a control freak, the hack it took to make those arrows appear was global for all number inputs on the whole page. We thought it would be ok since there we didn't realize the color choose had number inputs.

**Comment by Drock54651** [comment]
Implemented a new color picker.
