### ISSUE TITLE
Selecting an item to move it changes selection before moving

### ISSUE THREAD

**Issue by Randoom97** [SynBioDex/SBOLCanvas#134]
Before selection
![image](https://user-images.githubusercontent.com/8031223/95685911-0888c080-0bb8-11eb-8fd7-3f0c5bacb23e.png)
After clicking to start moving
![image](https://user-images.githubusercontent.com/8031223/95685941-29e9ac80-0bb8-11eb-9b13-5dadcc338911.png)

**Comment by cjmyers** [comment]
cannot reproduce
