### ISSUE TITLE
Hotkey detection woes (see comment)

### ISSUE THREAD

**Issue by Samonella7** [SynBioDex/SBOLCanvas#14]
Delete/backspace delete cells when:
    - Editing text of a on-canvas text box
    - Editing various fields in Info menu (for example version number)
(Hard to reproduce) Canvas hotkeys do not work recently after leaving a Design Menu input box

**Comment by Samonella7** [comment]
- Editing various fields in Info menu (for example version number)

This part has been fixed

**Comment by jaearl** [comment]
The issues cited have been fixed in previous commits.
