### ISSUE TITLE
Restructure frontend directories

### ISSUE THREAD

**Issue by Randoom97** [SynBioDex/SBOLCanvas#167]
Currently all services and components are just under the src/app directory. This makes finding files a pain for anyone who doesn't know where everything is. I would suggest setting things up like

* src/app/components/popups
* src/app/components/inline (or whatever name makes sense for non-popups)
* src/app/services/loginService (directory would contain login.service.ts and login.service.spec.ts)
* etc...

This would definitely mess with imports, but most of those should be  changed from relative paths ('../file.ts') to absolute paths.

**Comment by cjmyers** [comment]
Sounds good to me.
