### ISSUE TITLE
Error trying to upload a design to SBH

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLCanvas#174]
I got the following error while trying to upload a design to SBH:

<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException utils.MxToSBOL.getOrCreateParticipantFC(MxToSBOL.java:913) utils.MxToSBOL.addParticipant(MxToSBOL.java:863) utils.MxToSBOL.linkModuleDefinition(MxToSBOL.java:517) utils.MxToSBOL.setupDocument(MxToSBOL.java:209) utils.MxToSBOL.toSBOL(MxToSBOL.java:84) servlets.SynBioHub.doPost(SynBioHub.java:308) javax.servlet.http.HttpServlet.service(HttpServlet.java:652) javax.servlet.http.HttpServlet.service(HttpServlet.java:733) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:259) org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:163) </pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.46</h3></body></html>

**Comment by LukasBuecherl** [comment]
Same as #198
