### ISSUE TITLE
Complex molecule displays "http" as its name

### ISSUE THREAD

**Issue by nwhitaker** [SynBioDex/SBOLCanvas#181]
I added a complex molecule to the page, added a display ID and name and interaction lines, and custom colors. While I was doing this, everything looked good. But somehow, very soon, the display name was gone, and the name "http" was displayed. When I hovered over the molecule, it showed a showed web address (something like http://sbolcanvas/complexprotein"). When I went to the sidebar to try to fix the name, the sidebar was blank--no controls there at all.

To fix this, I deleted and recreated the complex molecule.

A while later, during the same session, the same thing happened with another complex molecule I created.

**Comment by joco0061** [comment]
I am also having this issue. When I place a macromolecule and name it it displays correctly for a time, and then eventually is replaces with an https link. I think it may be happening right after dragging the component around. Does not seem to revert, must be deleted and replaced.

**Comment by joco0061** [comment]
Actually, if you delete and then press Ctrl+Z it comes back with the name.

**Comment by nwhitaker** [comment]
Good to know. Thanks!

**Comment by cjmyers** [comment]
Cannot reproduce
