### ISSUE TITLE
Upload to SynBioHub throws error

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioDex/SBOLCanvas#182]
After creating a design I tried to upload it to SynBioHub. After clicking File -> Upload I get the following error:

<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException utils.MxToSBOL.linkModuleDefinition(MxToSBOL.java:469) utils.MxToSBOL.setupDocument(MxToSBOL.java:220) utils.MxToSBOL.toSBOL(MxToSBOL.java:86) servlets.SynBioHub.doPost(SynBioHub.java:308) javax.servlet.http.HttpServlet.service(HttpServlet.java:681) javax.servlet.http.HttpServlet.service(HttpServlet.java:764) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:264) org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:168) </pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.52</h3></body></html>

**Comment by geoffbaldwin** [comment]
If I link each part to a synbiohub entry so that each component has a defined sequence, it still throws the same error on saving.
