### ISSUE TITLE
Multiple ssNA with empty displayId causes validation errors

### ISSUE THREAD

**Issue by yu-eric** [SynBioDex/SBOLCanvas#193]
When multiple ssNA parts are added without displayId, SBOLCanvas will throw a sbol-10204 strong validation error ([see image](https://files.slack.com/files-pri/T02B9P0JRSS-F02DX12ESG5/image.png)). Changing each to have a unique displayId fixed the issue.

**Comment by cjmyers** [comment]
No longer allow empty displayIds
