### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioDex/SBOLCanvas#195]
I'm confused about the difference between a Module and a Component and what changes if your design is rooted in one or the other. Could this be made a bit clearer in the tutorial text.
Am I correct in thinking that these classes have been merged in SBOL 3.0?
Is SBOL Canvas therefore still on SBOL 2.0?

**Comment by LukasBuecherl** [comment]
A module includes interactions compared to a component. SBOLCanvas currently utilizes SBOL 2.0. With SBOL 3.0 these classes got merged. So it should get clearer when SBOLCanvas switches to SBOL 3.0.
