### ISSUE TITLE
Glyphs on imported parts

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioDex/SBOLCanvas#197]
When parts are imported from e.g. Cello repository, they are annotated correctly, e.g. Ter, but the glyph is just a straight line, it doesn't show it as a Terminator. This is also true for other part types e.g. promoter
![image](https://user-images.githubusercontent.com/22892335/140753265-defeb21c-e924-4ddf-b4e3-3736a88f0dc9.png)

**Comment by cjmyers** [comment]
Same as #126
