### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioDex/SBOLCanvas#198]
I was trying to upload a design into my collection at synbiohub.org, or save to a local file and got this error.
This seems extremely variable and unpredictable. Sometimes I can save files and sometimes I can't, but once it stops saving then there seems to be no recovery. Even brand new files sometimes don't save or upload.

I've been testing this, when I reload or open SBOL Canvas I can save the file. As soon as I go File>New Module Design or File>New Component Design, I get the error message when trying to save the file - this is even withuot putting anything in the design. This is repeatable across Chrome, Edge and Firefox. This means it is impossible to create a new component design or enumerate a component design.

Error
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Index: 2, Size: 2</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.IndexOutOfBoundsException: Index: 2, Size: 2 java.util.ArrayList.rangeCheck(ArrayList.java:659) java.util.ArrayList.get(ArrayList.java:435) utils.MxToSBOL.loadDictionary(MxToSBOL.java:994) utils.MxToSBOL.setupDocument(MxToSBOL.java:143) utils.MxToSBOL.toSBOL(MxToSBOL.java:86) servlets.SynBioHub.doPost(SynBioHub.java:321) javax.servlet.http.HttpServlet.service(HttpServlet.java:681) javax.servlet.http.HttpServlet.service(HttpServlet.java:764) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:264) org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:168) </pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.52</h3></body></html>

**Comment by LukasBuecherl** [comment]
Same as #182
