### ISSUE TITLE
After adding interaction cannot edit nodes anymore

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLCanvas#221]
When you add an interaction to an interaction node, then try to select the molecule to edit its name, it show the molecule Info but still the interaction, so you cannot edit the molecule name.

**Comment by zachsents** [comment]
This was happening when there is no interaction role that matches the interaction type of a glyph. 
[Fixed how this case was being handled by the frontend here.](https://github.com/SynBioDex/SBOLCanvas/commit/d195359283786d050e9eb259c159328767e9a703)
[The backend was also not including Process in the interaction roles. Fixed here.](https://github.com/SynBioDex/SBOLCanvas/commit/b13ae90e4e2cb8fdcde95551b82e47f719de42b8)
