### ISSUE TITLE
Login for Import Component required 

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioDex/SBOLCanvas#224]
It is not possible to download component information from public repositories from SynBioHub. The window is stuck loading the information without anything happening. The issue is most likely in line 257 in *https://github.com/SynBioDex/SBOLCanvas/SBOLCanvasBackend/src/servlets/SynBioHub.java*

**Comment by keithjac88** [comment]
This issue seems to be ongoing.  Was a fix or work around implemented here?

**Comment by cjmyers** [comment]
We recently removed public access to synbiohub.org.  You now need to login to access information.  We had to make this change because bots were accessing SynBioHub excessively causing it to crash.
