### ISSUE TITLE
Messed up Aptmeter glyph

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioDex/SBOLCanvas#227]
When I remove and then add the apt meter again the glyph is all messed up:

![Bug](https://user-images.githubusercontent.com/60665186/191312417-13b2e8cc-b263-4b69-a85d-06365e086544.png)

**Comment by cjmyers** [comment]
@LukasBuecherl is this still happening to you?

**Comment by LukasBuecherl** [comment]
I am not able to reproduce the issue so it seems to be fine
