### ISSUE TITLE
File>Export File - Error

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioDex/SBOLCanvas#231]
When I create a 'New component design', the design will not save to a local file and I get the following error. This happens with a clean new design that does not have any annotation or defined components.
![image](https://user-images.githubusercontent.com/22892335/201664465-9369f6b1-fd03-49e4-9f16-5fb7cbb4b226.png)

**Comment by zachsents** [comment]
Thanks Geoff. Looking into this.

**Comment by diegusleik** [comment]
Hi,
Thanks for this great development.
Similar issue again when exporting image.

Thanks in advance.

![image](https://github.com/SynBioDex/SBOLCanvas/assets/17186013/9e10bc28-8f73-40b6-b5b8-0f2740999975)
