### ISSUE TITLE
SBOL export should include backbone correctly and round trip

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLCanvas#250]
After adding a backbone, should be able to export SBOL, re-import and have the backbone show correctly

**Comment by LukasBuecherl** [comment]
When a SBOL file including a circular backbone is uploaded it should also be render correctly in canvas. This work is part of the backend-frontend connection.

**Comment by cjmyers** [comment]
MxToSBOL should include only one Circular component that is in one sequence constraint as the Object.
Also, add a type: http://identifiers.org/so/SO:0000988 to indicate it is circular.  Also, make sure the circular component uses this role http://identifiers.org/so/SO:0000755 (plasmid vector).

SBOLToMx should identify the type is circular, it should create the circular glyphs on both ends with the information details coming from the component with Role http://identifiers.org/so/SO:0000755 (plasmid vector).  Note that this should work even if the sequence constraint has the circular component as the subject OR object.
