### ISSUE TITLE
Add locus glyph support

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLCanvas#253]
There should be two glyphs for left and right locus and they should be added to the set of possible glyphs

**Comment by LukasBuecherl** [comment]
When opening SBOL Canvas, on the left hand side is a tab displaying the available sequence features (i.e. promoters, terminators, etc.). The glyphs are part of the SBOL visual ontology which can be found here (https://sbolstandard.org/visual-glyphs/). Recently, the circular backbone glyph was added to SBOL Canvas. Next, the chromosomal locus should be added. The implementation should be very closely related to the circular backbone.
