### ISSUE TITLE
access to synbiohub

### ISSUE THREAD

**Issue by Roycerda** [SynBioDex/SBOLCanvas#284]
I can't access synbiohub from sbolcanvas, therefore I can't do the job :c

**Comment by cjmyers** [comment]
Is it working now?

**Comment by Roycerda** [comment]
No, I have created an account in synbiohub, however I cannot access sbolcanvas, therefore I cannot finish the assignment even though I have already completed 98% of the Engineering Genetic Circuits: Design course

**Comment by cjmyers** [comment]
Hmm, it is working for me.  Can you provide a bit more detail about the issue?  Can you access https://sbolcanvas.org?  If so, when you add a part and select Import Component?  What is happening?  Are you able to login?  Can you see the collection you created?  I'm just trying to work out where you are getting stuck.

**Comment by Roycerda** [comment]
Yes, I can access sbolcanvas, however I cannot import data from synbiohub, I get *invalid login*, but I did create a synbiohub account on its official page.

**Comment by cjmyers** [comment]
Please let me know your login name on synbiohub.  Are you using your username or email address when you login?  Make sure to try both.

**Comment by Roycerda** [comment]
If I have tried several times with my username and email, however, I get the same problem that I cannot access.
If I don't finish the Engineering Genetic Circuits: Design course. Will they not give me the certificate even though I have completed 98% of the course? because I paid for the course :c

**Comment by cjmyers** [comment]
Can you give me a username you tried?  I want to check that username on synbiohub.org

Are you taking the course for credit or non-credit?

**Comment by Roycerda** [comment]
My username is Roy98 or my email is roy10998@gmail.com.
Yes, I am taking the course with credit, because I already paid for the course

**Comment by cjmyers** [comment]
This is very strange.  I can indeed see your account on synbiohub.org.  I just double checked, and I can login to my account via SBOLCanvas no problem, so I'm unable to reproduce your issue.  Any chance you can record your screen to show me exactly what is happening on your end?  

As a workaround, you don't need to login to download parts to your design.  You can just go find the parts manually by browsing the collections to find them.

**Comment by Roycerda** [comment]
![1](https://github.com/SynBioDex/SBOLCanvas/assets/94309017/1b52136d-0e73-46ea-8f77-ac789b90bb35)
![2](https://github.com/SynBioDex/SBOLCanvas/assets/94309017/e5e0475d-bd3a-4a19-8678-09606c88ae23)

**Comment by cjmyers** [comment]
You have double checked the password that you are using logs you in SynBioHub?

**Comment by Roycerda** [comment]
Yes several times, it still won't let me log in. Then I don't know what to do.

**Comment by cjmyers** [comment]
After logging in to SynBioHub select Profile and change your password to something simple and try again 

If this still does not work you can find the parts by browsing the iGEM collection and searching for them by id
