### ISSUE TITLE
I have an account in synbiohub, however I cannot access my private collection of saved parts in sbolcanvas.

### ISSUE THREAD

**Issue by davelotter** [SynBioDex/SBOLCanvas#288]

**Comment by cjmyers** [comment]
Please try to logout and login again in the component selection editor in SBOLCanvas.  If this does not work, please attach screenshots or link to movie of your issue.

**Comment by davelotter** [comment]
Was this issue resolved?  I dropped the class last month but would like to take the class if this issue has been fixed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cjmyers** [comment]
I closed it because you had not provided additional information, so I was hopeful that it had resolved for you.  If you are still having the issue, if you can post screenshots or link a movie showing the issue, it would help.  I'm not entirely sure what the issue is without more details.

**Comment by davelotter** [comment]
I’ll follow up with you with some video later today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cjmyers** [comment]
@davelotter Still cannot reproduce, so closing.  If you still have this issue, please reopen with more details.

**Comment by davelotter** [comment]
No problem.  I decided to postpone this class.

From: cjmyers ***@***.***>
Date: Wednesday, September 11, 2024 at 11:25 AM
To: SynBioDex/SBOLCanvas ***@***.***>
Cc: davelotter ***@***.***>, Mention ***@***.***>
Subject: Re: [SynBioDex/SBOLCanvas] I have an account in synbiohub, however I cannot access my private collection of saved parts in sbolcanvas. (Issue #288)

@davelotter<https://github.com/davelotter> Still cannot reproduce, so closing. If you still have this issue, please reopen with more details.
