### ISSUE TITLE
Error when i create collection

### ISSUE THREAD

**Issue by kurtkabeina09** [SynBioDex/SBOLCanvas#331]
![bug1](https://github.com/user-attachments/assets/a3f4135c-0cde-412d-92c3-104dae70867f)

**Comment by cjmyers** [comment]
SynBioHub may have been down. It is up now. Trying logging out and back in then try again

**Comment by Hatem-synbio** [comment]
I had the same issue yesterday as well.

**Comment by cjmyers** [comment]
Try now

**Comment by cjmyers** [comment]
If this happens again, please click "more details", so we can see the error
