### ISSUE TITLE
Exported images have low resolution

### ISSUE THREAD

**Issue by kevinwkeating** [SynBioDex/SBOLCanvas#42]
I exported a PNG to use in PowerPoint but it comes out pretty small so it is grainy when I enlarge it.

**Comment by eggrandio** [comment]
> I exported a PNG to use in PowerPoint but it comes out pretty small so it is grainy when I enlarge it.

If you export the image as a SVG file you can copy it into a powerpoint and it will not lose resolution as it will be a vector graph.

Higher resolution PNG files might be needed for other applications, though.
