### ISSUE TITLE
View top level strand data.

### ISSUE THREAD

**Issue by SamuelSauce** [SynBioDex/SBOLCanvas#47]
When an entire strand is selected there is no data on the info bar on the right side. Should be able to give it a name, view sequence, etc.

**Comment by jaearl** [comment]
This enhancement is completed in the Glyph-Aliasing branch. We will leave the issue open until we merge with 'final', which is our master branch. We might want to create an issue to clean up our branches and use a branch called 'master' as our master branch to avoid confusion.
