### ISSUE TITLE
Dockerize SBOLCanvas

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLCanvas#55]
Should put SBOLCanvas into a docker container that gets built and deployed automatically using github actions.  A good example of how this is done can be found here https://github.com/SynBioDex/SBOL-Validator

**Comment by cjmyers** [comment]
@SamuelSauce do you want to talk to Zach and try to get this going?

**Comment by SamuelSauce** [comment]
Fixed by pr #58
